# Generated by Django 4.0.3 on 2022-04-08 12:16

import data_importation.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_to_children', to='data_visualization.container')),
            ],
        ),
        migrations.CreateModel(
            name='ModelDashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('order', data_importation.fields.OrderField(blank=True)),
                ('headers', models.JSONField()),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_to_tables', to='data_visualization.container')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('order', data_importation.fields.OrderField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.OneToOneField(limit_choices_to={'model__in': ('table', 'chart')}, on_delete=django.db.models.deletion.CASCADE, related_name='visual_object_to_filter', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldToCompute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('field', models.CharField(default='', max_length=100)),
                ('calcul', models.CharField(choices=[('AVG', 'AVG'), ('MAX', 'MAX'), ('MIN', 'MIN'), ('COUNT', 'COUNT'), ('VAR', 'VAR'), ('SUM', 'SUM')], default='COUNT', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_to_compute', to='data_visualization.filter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='container',
            name='model_dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_dashboard_to_containers', to='data_visualization.modeldashboard'),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('order', data_importation.fields.OrderField(blank=True)),
                ('parameters', models.JSONField()),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_to_charts', to='data_visualization.container')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
