# Generated by Django 4.0.3 on 2022-04-22 20:56

import data_importation.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data_visualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_dashboard', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_to_dashboard', to='data_visualization.modeldashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('label', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('order', data_importation.fields.OrderField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_to_widgets', to='data_visualization.container')),
                ('content_type', models.OneToOneField(limit_choices_to={'model__in': ('table', 'chart', 'value')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='filter',
            name='content_type',
        ),
        migrations.AlterModelOptions(
            name='chart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.RemoveField(
            model_name='chart',
            name='container',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='table',
            name='container',
        ),
        migrations.RemoveField(
            model_name='table',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='order',
        ),
        migrations.RemoveField(
            model_name='table',
            name='title',
        ),
        migrations.AddField(
            model_name='chart',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FieldToCompute',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.AddField(
            model_name='value',
            name='widget',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_to_values', to='data_visualization.widget'),
        ),
        migrations.AddField(
            model_name='chart',
            name='widget',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_to_charts', to='data_visualization.widget'),
        ),
        migrations.AddField(
            model_name='table',
            name='widget',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_to_tables', to='data_visualization.widget'),
        ),
    ]
