# Generated by Django 4.0.3 on 2022-04-08 12:16

import data_reference.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=6)),
                ('label', models.CharField(default='', max_length=100)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
            ],
            bases=(models.Model, data_reference.models.Amount),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=17)),
                ('product', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=255)),
                ('account', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField(default=0, null=True)),
                ('credit', models.FloatField(default=0, null=True)),
                ('key', models.CharField(max_length=17, unique=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_reference.agency')),
            ],
            bases=(models.Model, data_reference.models.Amount),
        ),
    ]
