# Generated by Django 4.0.3 on 2022-06-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data_reference', '0002_alter_transaction_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('model_data', models.ForeignKey(limit_choices_to={'app_label__icontains': 'data_reference'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('model_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_to_fields', to='data_reference.modeltable')),
            ],
        ),
    ]
