# Generated by Django 4.0.3 on 2022-06-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_reference', '0003_modeltable_column'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Column',
            new_name='ModelColumn',
        ),
    ]
