# Generated by Django 4.0.3 on 2022-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_reference', '0004_rename_column_modelcolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltable',
            name='model_data',
        ),
        migrations.RemoveField(
            model_name='modeltable',
            name='object_id',
        ),
        migrations.AddField(
            model_name='modeltable',
            name='model_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
