# Generated by Django 4.0.3 on 2022-06-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_reference', '0005_remove_modeltable_model_data_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelcolumn',
            unique_together={('name', 'model_table')},
        ),
    ]
