# Generated by Django 4.0.3 on 2022-04-08 12:16

import data_importation.fields
import data_importation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(default='', max_length=100)),
                ('sheet_name', models.CharField(default='', max_length=100)),
                ('order', data_importation.fields.OrderField(blank=True)),
                ('base_excel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_to_excel_cells', to='data_importation.baseexcel')),
                ('previous_cell', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_cell', to='data_importation.cells')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RegularExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('expression', models.CharField(default='', max_length=255)),
                ('comment', models.TextField(default='')),
                ('is_splitter', models.BooleanField(default=False)),
                ('is_dependant', models.BooleanField(default=False)),
                ('can_extract_data', models.BooleanField(default=True)),
                ('base_text', models.ForeignKey(limit_choices_to={'model__in': ('basetext', 'basertf', 'baseexcel', 'cells')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('previous_reg_exp', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_reg_exp', to='data_importation.regularexpression')),
            ],
        ),
        migrations.CreateModel(
            name='BaseRTF',
            fields=[
                ('basetext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_importation.basetext')),
            ],
            bases=('data_importation.basetext',),
        ),
        migrations.CreateModel(
            name='ReplacementField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[], default='', max_length=100)),
                ('attr_name', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
                ('format', models.CharField(choices=[('DATE', 'DATE'), ('DATETIME', 'DATETIME'), ('FLOAT', 'FLOAT'), ('INT', 'INT'), ('STRING', 'STRING')], default='', max_length=100)),
                ('reg_expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_to_fields', to='data_importation.regularexpression')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelImportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('TXT', 'TXT'), ('RTF', 'RTF'), ('EXCEL', 'EXCEL'), ('CSV', 'CSV')], max_length=100)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('table_type', models.ForeignKey(limit_choices_to={'model__in': ('basetext', 'basertf', 'baseexcel')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Importation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to=data_importation.models.import_upload_directory)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('model_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_importation.modelimportation')),
            ],
        ),
        migrations.CreateModel(
            name='ConcernedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concerned_table', models.CharField(choices=[], max_length=100)),
                ('linked_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_to_table', to='data_importation.concernedtable')),
                ('model_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerned_tables', to='data_importation.modelimportation')),
            ],
        ),
        migrations.CreateModel(
            name='CellsReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(choices=[], default='', max_length=100)),
                ('attr_name', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
                ('format', models.CharField(choices=[('DATE', 'DATE'), ('DATETIME', 'DATETIME'), ('FLOAT', 'FLOAT'), ('INT', 'INT'), ('STRING', 'STRING')], default='', max_length=100)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells_to_fields', to='data_importation.cells')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cells',
            name='reg_expression',
            field=models.ForeignKey(blank=True, limit_choices_to={'base_text__model__in': ('cells',)}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_to_cells', to='data_importation.regularexpression'),
        ),
    ]
