# Generated by Django 4.0.3 on 2022-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellsreplacement',
            name='table',
            field=models.CharField(choices=[('agency', 'agency'), ('balance', 'balance'), ('card', 'card'), ('transaction', 'transaction')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='concernedtable',
            name='concerned_table',
            field=models.CharField(choices=[('agency', 'agency'), ('balance', 'balance'), ('card', 'card'), ('transaction', 'transaction')], max_length=100),
        ),
        migrations.AlterField(
            model_name='replacementfield',
            name='table',
            field=models.CharField(choices=[('agency', 'agency'), ('balance', 'balance'), ('card', 'card'), ('transaction', 'transaction')], default='', max_length=100),
        ),
    ]
