# Generated by Django 4.0.3 on 2022-05-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_importation', '0002_alter_cellsreplacement_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelimportation',
            unique_together={('name', 'format')},
        ),
    ]
