# Generated by Django 4.0.3 on 2022-05-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_importation', '0003_alter_modelimportation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importation',
            name='model_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_importation.modelimportation'),
        ),
    ]
