# Generated by Django 4.0.3 on 2022-06-01 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data_importation', '0005_rename_filename_importation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelimportation',
            name='table_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('basetext', 'basertf', 'baseexcel', 'cells')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
