# Generated by Django 4.0.3 on 2022-04-08 12:16

import data_importation.fields
import data_reporting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(default='', max_length=100)),
                ('cell', models.CharField(default='', max_length=100)),
                ('order', data_importation.fields.OrderField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FieldToCompute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('field', models.CharField(default='', max_length=100)),
                ('calcul', models.CharField(choices=[('AVG', 'AVG'), ('MAX', 'MAX'), ('MIN', 'MIN'), ('COUNT', 'COUNT'), ('VAR', 'VAR'), ('SUM', 'SUM')], default='COUNT', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=data_reporting.models.path_upload_to)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('order', data_importation.fields.OrderField(blank=True)),
                ('sheet_name', models.CharField(default='', max_length=100)),
                ('cell', models.CharField(default='', max_length=100)),
                ('data', models.JSONField()),
                ('model_reporting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_reporting_to_tables', to='data_reporting.modelreporting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=data_reporting.models.path_upload_to)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('model_reporting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_to_reporting', to='data_reporting.modelreporting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReplacementCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(default='', max_length=100)),
                ('row', models.CharField(default='', max_length=100)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_to_excel_cell', to='data_reporting.fieldtocompute')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('order', data_importation.fields.OrderField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.OneToOneField(limit_choices_to={'app_label__icontains': 'data_reporting', 'model__in': ('cell', 'table', 'chart')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fieldtocompute',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_to_compute', to='data_reporting.filter'),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('order', data_importation.fields.OrderField(blank=True)),
                ('parameters', models.JSONField()),
                ('cell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_to_chart', to='data_reporting.cell')),
                ('model_reporting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mode_reporting_to_charts', to='data_reporting.modelreporting')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='model_reporting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_to_reporting', to='data_reporting.modelreporting'),
        ),
    ]
