# Generated by Django 4.0.3 on 2022-04-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='table',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='table',
            name='sheet_name',
        ),
    ]
