# Generated by Django 4.0.3 on 2022-06-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_reporting', '0003_remove_replacementcell_data_cell_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='data',
            new_name='columns',
        ),
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
