# Generated by Django 4.0.3 on 2022-06-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_reporting', '0005_filter_field_filter_operator_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='columns',
            field=models.CharField(default='', max_length=100),
        ),
    ]
